name: Run Python
on:
    push:
    schedule: 
    - cron: 0 0 * * * #crontab guru格式 每小時設定排程時間

jobs:

    build:
        name: run py1
        runs-on: ubuntu-latest #執行的環境
        steps:
        - uses: actions/checkout@v2
        - name: Run python
          run: |
              python3 test.py